name: Generate Binaries

on: [push]

jobs:
  build:
     ##results in binaries that work with Debian Stretch/Buster
    runs-on: ubuntu-16.04
    container: 'debian:9'
    
    steps:
    - uses: actions/checkout@v1
    - name: make output directory if needed
      run: mkdir bins || exit 0
    - name: update apt
      run: apt-get update
    - name: ensure build packages are installed
      run: apt-get -y install libncurses5-dev build-essential git crossbuild-essential-powerpc crossbuild-essential-armel crossbuild-essential-armhf crossbuild-essential-arm64
    - name: build armhf binary
      run: make CROSS_COMPILE="arm-linux-gnueabihf-"
    - name: copy armhf bin to output directory
      run: cp phytool bins/phytool-armhf
    - name: make clean
      run: make clean
    - name: build armel binary
      run: make CROSS_COMPILE="arm-linux-gnueabi-"
    - name: copy armel bin to output directory
      run: cp phytool bins/phytool-armel
    - name: make clean
      run: make clean
    - name: build powerpc binary
      run: make CROSS_COMPILE="powerpc-linux-gnu-"
    - name: copy powerpc bin to output directory
      run: cp phytool bins/phytool-powerpc
    - name: make clean
      run: make clean
    - name: build arm64 binary
      run: make CROSS_COMPILE="aarch64-linux-gnu-"
    - name: copy arm64 bin to output directory
      run: cp phytool bins/phytool-arm64
    - name: make clean
      run: make clean
    - name: build amd64 binary
      run: make
    - name: copy amd64 bin to output directory
      run: cp phytool bins/phytool-amd64
    - name: set git user name
      run: git config user.name "workflow@github" 
    - name: set git user email
      run: git config user.email "workflow@github"
    - name: add new files to repo if needed
      run: git add bins/*
    - name: commit new files
      run: git commit -a -m "commit binaries built from latest source" || exit 0
    - name: push changes
      run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master


